import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { voice_id, text } = body;

    if (!voice_id || !text) {
      return NextResponse.json(
        { error: 'Missing voice_id or text' },
        { status: 400 }
      );
    }

    // TESTING MODE: Return simulated response for dashboard testing
    // This allows testing the UI without needing the Python backend
    // TODO: Implement actual Edge TTS integration when ready for production

    // Create a mock audio blob (in production, this would be generated by Edge TTS)
    const mockAudioData = new Uint8Array(1000); // Mock audio data
    const blob = new Blob([mockAudioData], { type: 'audio/mpeg' });
    const audioUrl = URL.createObjectURL(blob);

    // Simulate processing delay
    await new Promise(resolve => setTimeout(resolve, 1000));

    return NextResponse.json({
      success: true,
      audio_url: audioUrl,
      voice_id: voice_id,
      text: text,
      mock: true, // Flag indicating this is test data
      message: 'This is a simulated audio for testing. Backend integration coming soon.'
    });

  } catch (error: any) {
    console.error('Voice generation error:', error);
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    );
  }
}
